name: Continuous Integration

on:
  push:
    branches:
      - main
      - stable
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno fmt
        run: deno fmt --check

  testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Cache deno
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('deps.ts') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno test
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_ID: ${{ secrets.BOT_ID }}
        run: deno test -A
