name: Continuous Integration

on:
  push:
    branches:
      - main
      - stable
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno fmt
        run: deno fmt --check

  testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Cache deno
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('deps.ts') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno test
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_ID: ${{ secrets.BOT_ID }}
        run: deno test -A
