name: Continuous Integration

on:
  push:
    branches:
      - main
      - stable
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno fmt
        run: deno fmt --check

  testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Cache deno
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # tag=v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('deps.ts') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno test
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_ID: ${{ secrets.BOT_ID }}
        run: deno test -A
