name: Continuous Integration

on:
  push:
    branches:
      - main
      - stable
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: denoland/setup-deno@v2.0.5
        with:
          deno-version: 2.x
      - name: Deno fmt
        run: deno fmt --check

  testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Cache deno
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('deps.ts') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno

      - uses: denoland/setup-deno@v2.0.5
        with:
          deno-version: 2.x
      - name: Deno test
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_ID: ${{ secrets.BOT_ID }}
        run: deno test -A
